baseURL = "https://blog.jhnr.ch/"
languageCode = "en-us"
title = "Stefan Johner"
theme = "archie"
copyright = "© Stefan Johner"
relativeURLs = true
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[permalinks]
    blog = "/:year/:month/:day/:slug/"
    singles = "/:slug/"

[params]
    mode="toggle" # color-mode → light,dark,toggle or auto
    useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
    subtitle = "Working with Azure Cloud. Likes cheese, chocolate and [Burgdorfer Bier](https://burgdorferbier.ch/). Co-Organizer of [Azure Bern User Group](https://www.meetup.com/de-DE/azure-cloud-bern-user-group/) and [Azure Bootcamp Switzerland](https://azurebootcamp.ch)"
    mathjax = true # enable MathJax support
    katex = true # enable KaTeX support

[[params.social]]
    name = "GitHub"
    icon = "simple:github"
    url = "https://github.com/sjohner"

[[params.social]]
    name = "Bluesky"
    icon = "simple:bluesky"
    url = "https://bsky.app/profile/jhnr.ch"

[[params.social]]
    name = "LinkedIn"
    icon = "simple:linkedin"
    url = "https://linkedin.com/in/stefanjohner"

[[menu.main]]
    name = "All posts"
    url = "/blog"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 3

[[menu.main]]
    url = "/privacy-policy/"
    name = "Privacy Policy"
    weight = 4
