baseURL = "https://blog.jhnr.ch/"
languageCode = "en-us"
title = "Stefan Johner"
theme = "hyde"
disqusShortname = "jhnr"
googleAnalytics = "UA-72698700-1"
relativeURLs = true

[permalinks]
  blog = "/:year/:month/:day/:title/"
  singles = "/:title/"

[params]
    themeColor = "theme-base-0d"
    description = "Working with #Azure. Microsoft MVP. Likes cheese, chocolate and <a href="https://twitter.com/burgdorferbier">@burgdorferbier</a>. Runs <a href="http://itproch.expertslive.cafe">Experts Live Café Switzerland</a>"
    copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
    creativeCommons = "by-sa"
    github = "sjohner"
    twitter = "johnerstefan"
    linkedin = "sjohner"


    # Minimal theme params
    #author = "Stefan Johner"
    #profilePic = "images/avatar.png"
    #githubUsername = "sjohner"
    #accent = "#007acc"
    #showBorder = true
    #backgroundColor = "white"
    #font = "Raleway" # should match the name on Google Fonts!
    #highlight = true
    #highlightStyle = "solarized-dark"
    #highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    

[[menu.main]]
    url = "/privacy-policy"
    name = "Privacy Policy"
    weight = 1

#[[menu.main]]
#    url = "/blog/"
#    name = "Blog"
#    weight = 2
#
#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 3
#
#[[menu.main]]
#    url = "/event/"
#    name = "Community Events"
#    weight = 3
