baseURL = "https://blog.jhnr.ch/"
languageCode = "en-us"
title = "Stefan Johner"
theme = "hyde"
disqusShortname = "jhnr"
googleAnalytics = "UA-72698700-1"
relativeURLs = true

[permalinks]
  blog = "/:year/:month/:day/:slug/"
  singles = "/:slug/"

[params]
    themeColor = "theme-base-0d"
    description = "Working with Cloud. Microsoft MVP. Likes cheese, chocolate and @burgdorferbier. Runs Experts Live Café Switzerland"
    copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
    creativeCommons = "by-sa"
    socialSharePrivacy = true
    github = "sjohner"
    twitter = "johnerstefan"
    linkedin = "sjohner"   

[[menu.main]]
    url = "/privacy-policy/"
    name = "Privacy Policy"
    weight = 1

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
  [privacy.speakerDeck]
    disable = false
  [privacy.twitter]
    disable = false
    enableDNT = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
