baseURL = "https://blog.jhnr.ch/"
languageCode = "en-us"
title = "Stefan Johner"
theme = "hyde"
disqusShortname = "sjohner"
googleAnalytics = " UA-72698700-1"
relativeURLs = true

[permalinks]
  blog = "/:year/:month/:day/:title/"

[params]
    themeColor = "theme-base-0d"
    description = "Working with #Azure. Microsoft MVP. Likes cheese, chocolate and @burgdorferbier. Runs Experts Live Café Switzerland"
    copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

    # Minimal theme params
    #author = "Stefan Johner"
    #profilePic = "images/avatar.png"
    #githubUsername = "sjohner"
    #accent = "#007acc"
    #showBorder = true
    #backgroundColor = "white"
    #font = "Raleway" # should match the name on Google Fonts!
    #highlight = true
    #highlightStyle = "solarized-dark"
    #highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    

#[[menu.main]]
#    url = "/"
#    name = "Home"
#    weight = 1

#[[menu.main]]
#    url = "/blog/"
#    name = "Blog"
#    weight = 2

#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 3
#
#[[menu.main]]
#    url = "/event/"
#    name = "Community Events"
#    weight = 3
#
# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/sjohner/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/johnerstefan/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/sjohner/"
    name = "linkedin"
    weight = 4
